<a href="https://colab.research.google.com/github/peperjet/deep-learning/blob/main/Word_Embedding/9_8_pretrained_word_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

이 자료는 위키독스 '딥 러닝을 이용한 자연어 처리 입문'의 사전 훈련된 워드 임베딩 튜토리얼 자료입니다.

링크 : https://wikidocs.net/33793

1. Kearas Embedding layer 케라스 임베딩 레이어


In [16]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [17]:
sentences = ['nice great best amazing', 'stop lies', 'pitiful nerd', 'excellent work', 'supreme quality', 'bad', 'highly respectable']
y_train = [1, 0, 0, 1, 1, 0, 1]

In [18]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
vocab_size = len(tokenizer.word_index) + 1
print(vocab_size)

16


In [19]:
X_encoded = tokenizer.texts_to_sequences(sentences)
print(X_encoded)

[[1, 2, 3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13], [14, 15]]


In [20]:
max_len = max(len(l) for l in X_encoded)
print(max_len)

4


In [21]:
X_train = pad_sequences(X_encoded, maxlen=max_len, padding='post')
y_train = np.array(y_train)
print(X_train)

[[ 1  2  3  4]
 [ 5  6  0  0]
 [ 7  8  0  0]
 [ 9 10  0  0]
 [11 12  0  0]
 [13  0  0  0]
 [14 15  0  0]]


In [22]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten

embedding_dim = 4

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim, input_length=max_len))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


이 셀은 현재 자료가 위키독스 '딥 러닝을 이용한 자연어 처리 입문' 튜토리얼의 일부임을 알려주는 주석입니다. 어떤 자료를 참고하고 있는지 명시하고 있습니다.

이 셀은 텍스트 데이터를 처리하고 딥러닝 모델을 만들기 위해 필요한 라이브러리들을 불러옵니다:
- `numpy`: 숫자 배열을 다루는 데 사용됩니다.
- `Tokenizer`: 텍스트를 숫자로 변환하는 데 사용됩니다.
- `pad_sequences`: 길이가 다른 텍스트 시퀀스들을 일정한 길이로 맞춰주는 데 사용됩니다.

이 셀에서는 분석할 문장들(`sentences`)과 각 문장의 긍정/부정(1/0)을 나타내는 라벨(`y_train`)을 정의합니다. 예를 들어, 'nice great best amazing'은 긍정(1)이고, 'stop lies'는 부정(0)입니다.

이 셀은 `Tokenizer` 객체를 생성하고, 정의된 문장들(`sentences`)을 학습시킵니다. 학습을 통해 각 단어에 고유한 숫자를 부여하고(`tokenizer.fit_on_texts`), 전체 단어의 개수(`vocab_size`)를 계산합니다. `vocab_size`는 임베딩 레이어의 크기를 결정하는 데 사용됩니다.

이 셀은 학습된 `Tokenizer`를 사용하여 `sentences`의 각 단어를 숫자로 변환합니다. 그 결과 각 문장은 숫자의 시퀀스(`X_encoded`)로 표현됩니다. 예를 들어, 'nice great best amazing'은 `[1, 2, 3, 4]`와 같이 변환됩니다.

이 셀은 `X_encoded`에 있는 숫자 시퀀스들 중에서 가장 긴 시퀀스의 길이를 찾습니다. 이 `max_len` 값은 모든 시퀀스의 길이를 통일시킬 때 기준이 됩니다.

이 셀은 `pad_sequences` 함수를 사용하여 `X_encoded`의 모든 시퀀스 길이를 `max_len`에 맞춰줍니다. 짧은 시퀀스에는 0을 뒤에 추가하여 길이를 맞춥니다 (`padding='post'`). 이렇게 변환된 데이터를 `X_train`에 저장하고, `y_train`은 NumPy 배열로 변환합니다.

이 셀은 Keras를 사용하여 딥러닝 모델을 구축합니다:
- `Sequential()`: 순차적인 레이어 스택으로 구성된 모델을 만듭니다.
- `Embedding(vocab_size, embedding_dim, input_length=max_len)`: 단어를 저차원의 밀집 벡터(임베딩 벡터)로 변환하는 레이어입니다. `vocab_size`는 전체 단어의 개수, `embedding_dim`은 임베딩 벡터의 차원, `input_length`는 입력 시퀀스의 최대 길이입니다.
- `Flatten()`: 임베딩 레이어의 출력을 1차원 배열로 평탄화하여 다음 레이어에 전달합니다.
- `Dense(1, activation='sigmoid')`: 출력 레이어입니다. 이진 분류(긍정/부정)를 위해 1개의 뉴런과 'sigmoid' 활성화 함수를 사용합니다. 'sigmoid'는 0과 1 사이의 값을 출력하여 확률을 나타냅니다.

In [23]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
model.fit(X_train, y_train, epochs=100, verbose=2)

Epoch 1/100
1/1 - 1s - 1s/step - acc: 0.5714 - loss: 0.6903
Epoch 2/100
1/1 - 0s - 45ms/step - acc: 0.7143 - loss: 0.6887
Epoch 3/100
1/1 - 0s - 44ms/step - acc: 0.7143 - loss: 0.6871
Epoch 4/100
1/1 - 0s - 45ms/step - acc: 0.7143 - loss: 0.6855
Epoch 5/100
1/1 - 0s - 45ms/step - acc: 0.7143 - loss: 0.6839
Epoch 6/100
1/1 - 0s - 47ms/step - acc: 0.8571 - loss: 0.6823
Epoch 7/100
1/1 - 0s - 47ms/step - acc: 0.8571 - loss: 0.6807
Epoch 8/100
1/1 - 0s - 49ms/step - acc: 0.8571 - loss: 0.6791
Epoch 9/100
1/1 - 0s - 46ms/step - acc: 0.8571 - loss: 0.6775
Epoch 10/100
1/1 - 0s - 46ms/step - acc: 0.8571 - loss: 0.6759
Epoch 11/100
1/1 - 0s - 51ms/step - acc: 0.8571 - loss: 0.6743
Epoch 12/100
1/1 - 0s - 46ms/step - acc: 0.8571 - loss: 0.6727
Epoch 13/100
1/1 - 0s - 48ms/step - acc: 0.8571 - loss: 0.6711
Epoch 14/100
1/1 - 0s - 44ms/step - acc: 0.8571 - loss: 0.6695
Epoch 15/100
1/1 - 0s - 44ms/step - acc: 0.8571 - loss: 0.6679
Epoch 16/100
1/1 - 0s - 46ms/step - acc: 0.8571 - loss: 0.6662
Epo

2. 사전 훈련된 GloVe 사용하기

In [24]:
from urllib.request import urlretrieve, urlopen
import gzip
import zipfile

In [27]:
import requests

url = "https://nlp.stanford.edu/data/glove.6B.50d.txt"
r = requests.get(url)

with open("glove.6B.50d.txt", "wb") as f:
    f.write(r.content)

용량, 다운로드 로딩 이슈로 일부만 다운로드...


In [29]:
embedding_dict = dict()

f = open('glove.6B.100d.txt', encoding="utf8")

for line in f:
    word_vector = line.split()
    word = word_vector[0]

    # 100개의 값을 가지는 array로 변환
    word_vector_arr = np.asarray(word_vector[1:], dtype='float32') #숫자로 변환
    embedding_dict[word] = word_vector_arr #딕셔너리에 저장
f.close()

print('%s개의 Embedding vector가 있습니다.' % len(embedding_dict))

400000개의 Embedding vector가 있습니다.


In [32]:
print(embedding_dict['respectable'])
print(len(embedding_dict['respectable']))

[-0.049773   0.19903    0.10585    0.1391    -0.32395    0.44053
  0.3947    -0.22805   -0.25793    0.49768    0.15384   -0.08831
  0.0782    -0.8299    -0.037788   0.16772   -0.45197   -0.17085
  0.74756    0.98256    0.81872    0.28507    0.16178   -0.48626
 -0.006265  -0.92469   -0.30625   -0.067318  -0.046762  -0.76291
 -0.0025264 -0.018795   0.12882   -0.52457    0.3586     0.43119
 -0.89477   -0.057421  -0.53724    0.25587    0.55195    0.44698
 -0.24252    0.29946    0.25776   -0.8717     0.68426   -0.05688
 -0.1848    -0.59352   -0.11227   -0.57692   -0.013593   0.18488
 -0.32507   -0.90171    0.17672    0.075601   0.54896   -0.21488
 -0.54018   -0.45882   -0.79536    0.26331    0.18879   -0.16363
  0.3975     0.1099     0.1164    -0.083499   0.50159    0.35802
  0.25677    0.088546   0.42108    0.28674   -0.71285   -0.82915
  0.15297   -0.82712    0.022112   1.067     -0.31776    0.1211
 -0.069755  -0.61327    0.27308   -0.42638   -0.085084  -0.17694
 -0.0090944  0.1109     0.

len : "respectable" 단어의 벡터 길이가 몇 개냐?

In [33]:
# 단어 집합 크기의 행과 100개의 열을 가지는 행렬 생성, 값은 전부 0으로 채워진다.
embedding_matrix = np.zeros((vocab_size, 100))
np.shape(embedding_matrix)

(16, 100)

In [34]:
print(tokenizer.word_index.items())

dict_items([('nice', 1), ('great', 2), ('best', 3), ('amazing', 4), ('stop', 5), ('lies', 6), ('pitiful', 7), ('nerd', 8), ('excellent', 9), ('work', 10), ('supreme', 11), ('quality', 12), ('bad', 13), ('highly', 14), ('respectable', 15)])


In [35]:
tokenizer.word_index['great']

2

In [36]:
print(embedding_dict['great'])

[-0.013786   0.38216    0.53236    0.15261   -0.29694   -0.20558
 -0.41846   -0.58437   -0.77355   -0.87866   -0.37858   -0.18516
 -0.128     -0.20584   -0.22925   -0.42599    0.3725     0.26077
 -1.0702     0.62916   -0.091469   0.70348   -0.4973    -0.77691
  0.66045    0.09465   -0.44893    0.018917   0.33146   -0.35022
 -0.35789    0.030313   0.22253   -0.23236   -0.19719   -0.0053125
 -0.25848    0.58081   -0.10705   -0.17845   -0.16206    0.087086
  0.63029   -0.76649    0.51619    0.14073    1.019     -0.43136
  0.46138   -0.43585   -0.47568    0.19226    0.36065    0.78987
  0.088945  -2.7814    -0.15366    0.01015    1.1798     0.15168
 -0.050112   1.2626    -0.77527    0.36031    0.95761   -0.11385
  0.28035   -0.02591    0.31246   -0.15424    0.3778    -0.13599
  0.2946    -0.31579    0.42943    0.086969   0.019169  -0.27242
 -0.31696    0.37327    0.61997    0.13889    0.17188    0.30363
 -1.2776     0.044423  -0.52736   -0.88536   -0.19428   -0.61947
 -0.10146   -0.26301  

In [38]:
for word, index in tokenizer.word_index.items():
  # 단어와 맵핑되는 사전 훈련된 임베딩 벡터값
  vector_value = embedding_dict.get(word)
  if vector_value is not None:
    embedding_matrix[index] = vector_value

In [39]:
embedding_matrix[2]

array([-0.013786  ,  0.38216001,  0.53236002,  0.15261   , -0.29694   ,
       -0.20558   , -0.41846001, -0.58437002, -0.77354997, -0.87866002,
       -0.37858   , -0.18516   , -0.12800001, -0.20584001, -0.22925   ,
       -0.42598999,  0.3725    ,  0.26076999, -1.07019997,  0.62915999,
       -0.091469  ,  0.70348001, -0.4973    , -0.77691001,  0.66044998,
        0.09465   , -0.44893   ,  0.018917  ,  0.33146   , -0.35021999,
       -0.35789001,  0.030313  ,  0.22253001, -0.23236001, -0.19719   ,
       -0.0053125 , -0.25848001,  0.58081001, -0.10705   , -0.17845   ,
       -0.16205999,  0.087086  ,  0.63028997, -0.76648998,  0.51618999,
        0.14072999,  1.01900005, -0.43136001,  0.46138   , -0.43584999,
       -0.47567999,  0.19226   ,  0.36065   ,  0.78987002,  0.088945  ,
       -2.78139997, -0.15366   ,  0.01015   ,  1.17980003,  0.15167999,
       -0.050112  ,  1.26259995, -0.77526999,  0.36030999,  0.95761001,
       -0.11385   ,  0.28035   , -0.02591   ,  0.31246001, -0.15

In [44]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten

model = Sequential()
e = Embedding(vocab_size, 100, weights=[embedding_matrix], input_length=max_len, trainable=False)

In [45]:
model.add(e)
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
model.fit(X_train, y_train, epochs=100, verbose=2)

Epoch 1/100
1/1 - 1s - 1s/step - acc: 0.2857 - loss: 0.7684
Epoch 2/100
1/1 - 0s - 54ms/step - acc: 0.4286 - loss: 0.7439
Epoch 3/100
1/1 - 0s - 54ms/step - acc: 0.4286 - loss: 0.7202
Epoch 4/100
1/1 - 0s - 54ms/step - acc: 0.4286 - loss: 0.6975
Epoch 5/100
1/1 - 0s - 54ms/step - acc: 0.4286 - loss: 0.6756
Epoch 6/100
1/1 - 0s - 57ms/step - acc: 0.4286 - loss: 0.6547
Epoch 7/100
1/1 - 0s - 58ms/step - acc: 0.5714 - loss: 0.6346
Epoch 8/100
1/1 - 0s - 78ms/step - acc: 0.5714 - loss: 0.6155
Epoch 9/100
1/1 - 0s - 60ms/step - acc: 0.5714 - loss: 0.5973
Epoch 10/100
1/1 - 0s - 61ms/step - acc: 0.5714 - loss: 0.5799
Epoch 11/100
1/1 - 0s - 59ms/step - acc: 0.5714 - loss: 0.5633
Epoch 12/100
1/1 - 0s - 61ms/step - acc: 0.5714 - loss: 0.5475
Epoch 13/100
1/1 - 0s - 54ms/step - acc: 0.5714 - loss: 0.5324
Epoch 14/100
1/1 - 0s - 54ms/step - acc: 0.5714 - loss: 0.5180
Epoch 15/100
1/1 - 0s - 56ms/step - acc: 0.5714 - loss: 0.5043
Epoch 16/100
1/1 - 0s - 61ms/step - acc: 0.7143 - loss: 0.4911
Epo

3. 사전 훈련된 Word2Vec 사용하기

In [51]:
!pip install gensim
import gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 38.0 MB/s eta 0:00:00


In [57]:
import gensim.downloader as api

word2vec_model = api.load("glove-wiki-gigaword-100")

[==================================================] 100.0% 128.1/128.1MB downloaded


In [58]:
print(word2vec_model['king'][:5])
print(word2vec_model.most_similar('king'))

[-0.32307 -0.87616  0.21977  0.25268  0.22976]
[('prince', 0.7682328820228577), ('queen', 0.7507690787315369), ('son', 0.7020888328552246), ('brother', 0.6985775232315063), ('monarch', 0.6977890729904175), ('throne', 0.6919989585876465), ('kingdom', 0.6811409592628479), ('father', 0.6802029013633728), ('emperor', 0.6712858080863953), ('ii', 0.6676074266433716)]


In [59]:
print(word2vec_model.vectors.shape) # 모델의 크기 확인

(400000, 100)


In [72]:
# 단어집합 크기의 행과 100개의 열을 가지는 행렬 생성, 값은 전부 0으로 채워진다
embedding_matrix = np.zeros((vocab_size, 100))
np.shape(embedding_matrix)

(16, 100)

In [62]:
def get_vector(word):
  if word in word2vec_model:
    return word2vec_model[word]

  else:
    return None

In [73]:
for word, index in tokenizer.word_index.items():
  # 단어와 맵핑되는 사전 훈련된 임베딩 벡터값
  vector_value = get_vector(word)
  if vector_value is not None:
    embedding_matrix[index] = vector_value

In [74]:
print(word2vec_model['nice'])

[-0.18554    0.047152   0.34867   -0.23114   -0.26083    0.63108
  0.55687    0.61622   -0.15437   -0.38381    0.12445   -0.26999
 -0.29196    0.1125     0.36035    0.70689   -0.33891   -0.2695
  0.17481    0.97048    0.23014    0.63168   -0.24543   -0.7289
  0.32517   -0.21118   -0.80354   -0.59863   -0.10182   -0.87826
 -0.80162    0.20999    0.64598   -0.38239    0.64512    0.73046
 -0.19881    0.35717    0.19135   -0.43686    0.75956   -0.66431
  0.34509   -1.0383    -0.50491    0.19976   -0.041208   0.16952
  0.17821   -0.84249    0.21992   -0.16474   -0.24669    0.34117
 -0.59713   -2.3434     0.31484    0.69668    0.53368   -0.62857
 -0.197      0.52241   -1.5903    -0.16475    0.62553   -0.094116
  0.0070705  0.22617   -0.45698   -0.53268    0.11573   -0.19052
  0.28086   -0.5591     0.35291    0.42552    0.47334   -0.41046
  0.47275    0.22753   -0.097073  -0.11809   -0.25613   -0.10689
 -1.2788    -0.085504   0.20205    0.23338   -0.52939   -0.49492
  0.15289   -0.31324    0.

In [75]:
print(word2vec_model['great'])

[-0.013786   0.38216    0.53236    0.15261   -0.29694   -0.20558
 -0.41846   -0.58437   -0.77355   -0.87866   -0.37858   -0.18516
 -0.128     -0.20584   -0.22925   -0.42599    0.3725     0.26077
 -1.0702     0.62916   -0.091469   0.70348   -0.4973    -0.77691
  0.66045    0.09465   -0.44893    0.018917   0.33146   -0.35022
 -0.35789    0.030313   0.22253   -0.23236   -0.19719   -0.0053125
 -0.25848    0.58081   -0.10705   -0.17845   -0.16206    0.087086
  0.63029   -0.76649    0.51619    0.14073    1.019     -0.43136
  0.46138   -0.43585   -0.47568    0.19226    0.36065    0.78987
  0.088945  -2.7814    -0.15366    0.01015    1.1798     0.15168
 -0.050112   1.2626    -0.77527    0.36031    0.95761   -0.11385
  0.28035   -0.02591    0.31246   -0.15424    0.3778    -0.13599
  0.2946    -0.31579    0.42943    0.086969   0.019169  -0.27242
 -0.31696    0.37327    0.61997    0.13889    0.17188    0.30363
 -1.2776     0.044423  -0.52736   -0.88536   -0.19428   -0.61947
 -0.10146   -0.26301  

In [76]:
print(embedding_matrix[2])

[-0.013786    0.38216001  0.53236002  0.15261    -0.29694    -0.20558
 -0.41846001 -0.58437002 -0.77354997 -0.87866002 -0.37858    -0.18516
 -0.12800001 -0.20584001 -0.22925    -0.42598999  0.3725      0.26076999
 -1.07019997  0.62915999 -0.091469    0.70348001 -0.4973     -0.77691001
  0.66044998  0.09465    -0.44893     0.018917    0.33146    -0.35021999
 -0.35789001  0.030313    0.22253001 -0.23236001 -0.19719    -0.0053125
 -0.25848001  0.58081001 -0.10705    -0.17845    -0.16205999  0.087086
  0.63028997 -0.76648998  0.51618999  0.14072999  1.01900005 -0.43136001
  0.46138    -0.43584999 -0.47567999  0.19226     0.36065     0.78987002
  0.088945   -2.78139997 -0.15366     0.01015     1.17980003  0.15167999
 -0.050112    1.26259995 -0.77526999  0.36030999  0.95761001 -0.11385
  0.28035    -0.02591     0.31246001 -0.15424     0.37779999 -0.13598999
  0.29460001 -0.31579     0.42943001  0.086969    0.019169   -0.27241999
 -0.31696001  0.37327     0.61997002  0.13889     0.17188001  0

In [79]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten, Input

model = Sequential()
model.add(Input(shape=(max_len,), dtype='int32'))
e = Embedding(vocab_size, 100, weights=[embedding_matrix], trainable=False)
model.add(e)
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
model.fit(X_train, y_train, epochs=100, verbose=2)

Epoch 1/100
1/1 - 1s - 716ms/step - acc: 0.4286 - loss: 0.7744
Epoch 2/100
1/1 - 0s - 46ms/step - acc: 0.5714 - loss: 0.7518
Epoch 3/100
1/1 - 0s - 46ms/step - acc: 0.5714 - loss: 0.7300
Epoch 4/100
1/1 - 0s - 46ms/step - acc: 0.5714 - loss: 0.7091
Epoch 5/100
1/1 - 0s - 45ms/step - acc: 0.5714 - loss: 0.6890
Epoch 6/100
1/1 - 0s - 113ms/step - acc: 0.5714 - loss: 0.6697
Epoch 7/100
1/1 - 0s - 75ms/step - acc: 0.5714 - loss: 0.6511
Epoch 8/100
1/1 - 0s - 45ms/step - acc: 0.5714 - loss: 0.6334
Epoch 9/100
1/1 - 0s - 48ms/step - acc: 0.7143 - loss: 0.6164
Epoch 10/100
1/1 - 0s - 45ms/step - acc: 0.7143 - loss: 0.6000
Epoch 11/100
1/1 - 0s - 47ms/step - acc: 0.7143 - loss: 0.5844
Epoch 12/100
1/1 - 0s - 140ms/step - acc: 0.8571 - loss: 0.5693
Epoch 13/100
1/1 - 0s - 46ms/step - acc: 0.8571 - loss: 0.5549
Epoch 14/100
1/1 - 0s - 45ms/step - acc: 0.8571 - loss: 0.5410
Epoch 15/100
1/1 - 0s - 49ms/step - acc: 0.8571 - loss: 0.5276
Epoch 16/100
1/1 - 0s - 45ms/step - acc: 0.8571 - loss: 0.514

In [80]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - acc: 1.0000 - loss: 0.1116
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - acc: 1.0000 - loss: 0.1102
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - acc: 1.0000 - loss: 0.1089
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - acc: 1.0000 - loss: 0.1075
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - acc: 1.0000 - loss: 0.1062
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - acc: 1.0000 - loss: 0.1049
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - acc: 1.0000 - loss: 0.1037
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 197ms/step - acc: 1.0000 - loss: 0.1024
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 226ms/step - acc: 1.0000 - loss: 0.1012
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - acc: 1.0000 - loss: 0.1000
